/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lib_prettygirls_nativeMethod_JniUtils */

#ifndef _Included_com_lib_prettygirls_nativeMethod_JniUtils
#define _Included_com_lib_prettygirls_nativeMethod_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lib_prettygirls_nativeMethod_JniUtils
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lib_prettygirls_nativeMethod_JniUtils_addInt
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
